apiVersion: apps/v1
kind: Deployment
metadata:
  name: chromadb
  labels:
    app: chromadb
spec:
  selector:
    matchLabels:
      app: chromadb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: chromadb
    spec:
      containers:
        - name: chromadb
          image: ghcr.io/chroma-core/chroma:latest
          env:
            - name: ANALYTICS_ANONYMOUS_ID
              value: ""
          command: ["uvicorn", "chromadb.app:app", "--host", "0.0.0.0", "--port", "8000"]
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: chromadb
  labels:
    app: chromadb
spec:
  ports:
    - port: 8000
  selector:
    app: chromadb
  clusterIP: None