apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "spring-mcp.fullname" . }}
  labels:
    {{- include "spring-mcp.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "spring-mcp.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "spring-mcp.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "spring-mcp.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://{{ include "spring-mcp.fullname" . }}-mysql:3306/{{ .Values.mysql.database }}
            - name: SPRING_DATASOURCE_USERNAME
              value: {{ .Values.mysql.username }}
            - name: SPRING_DATASOURCE_PASSWORD
              value: {{ .Values.mysql.password }}
            - name: SPRING_AI_VECTORSTORE_CHROMA_URL
              value: http://{{ include "spring-mcp.fullname" . }}-chromadb:{{ .Values.chromadb.port }}
            - name: SPRING_AI_OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: openai-api-key
                  key: api-key
            - name: SPRING_RABBITMQ_HOST
              value: {{ include "spring-mcp.fullname" . }}-rabbitmq
            - name: SPRING_RABBITMQ_USERNAME
              value: {{ .Values.rabbitmq.username }}
            - name: SPRING_RABBITMQ_PASSWORD
              value: {{ .Values.rabbitmq.password }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "spring-mcp.fullname" . }}
  labels:
    {{- include "spring-mcp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "spring-mcp.selectorLabels" . | nindent 4 }}