{{- if .Values.rabbitmq.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "spring-mcp.fullname" . }}-rabbitmq
  labels:
    {{- include "spring-mcp.labels" . | nindent 4 }}
    app.kubernetes.io/component: rabbitmq
spec:
  selector:
    matchLabels:
      {{- include "spring-mcp.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: rabbitmq
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "spring-mcp.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: "{{ .Values.rabbitmq.image }}"
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: {{ .Values.rabbitmq.username }}
            - name: RABBITMQ_DEFAULT_PASS
              value: {{ .Values.rabbitmq.password }}
          ports:
            - containerPort: 5672
            - containerPort: 15672
---)
apiVersion: v1
kind: Service
metadata:
  name: {{ include "spring-mcp.fullname" . }}-rabbitmq
  labels:
    {{- include "spring-mcp.labels" . | nindent 4 }}
    app.kubernetes.io/component: rabbitmq
spec:
  ports:
    - port: 5672
      name: amqp
    - port: 15672
      name: management
  selector:
    {{- include "spring-mcp.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: rabbitmq
  clusterIP: None
{{- end }}