{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "spring-mcp.fullname" . }}
  namespace: {{ .Values.serviceMonitor.namespace | default .Release.Namespace }}
  labels:
    {{- include "spring-mcp.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "spring-mcp.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: http
    interval: {{ .Values.serviceMonitor.interval }}
    path: {{ .Values.serviceMonitor.path }}
    scheme: http
    honorLabels: true
    scrapeTimeout: 30s
{{- end }}